version: '3.9'

networks:
  php80:
    external: false

volumes:
  mysql_data:

services:
  php80:
    build:
      context: ./php80
    image: php:80
    restart: always
    networks:
      - php80
    volumes: 
      - /opt/www:/opt/www
  nginx:
    build:
      context: ./nginx
    image: nginx:1.22
    restart: always
    networks:
      - php80
    volumes: 
      - /opt/www:/opt/www
      - $PWD/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/config/http.d:/etc/nginx/http.d
      - $PWD/nginx/config/stream.d:/etc/nginx/stream.d
      - $PWD/nginx/config/ssl:/etc/nginx/ssl
      - $PWD/nginx/config/htpasswd:/etc/nginx/htpasswd
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=suhua123
      - MYSQL_USER=test
      - MYSQL_PASSWORD=suhua123
      - MYSQL_DATABASE=test
    networks:
      - php80
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    cap_add:
      - SYS_NICE
