version: '3.9'

services:
  php74:
    build:
      context: ./php74
    image: php:74
    container_name: php74
    restart: always
    volumes: 
      - /www/web:/opt
  nginx:
    build:
      context: ./nginx
    image: nginx:1.22
    container_name: nginx
    restart: always
    volumes: 
      - /www/web:/opt
      - $PWD/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/config/http.d:/etc/nginx/http.d
      - $PWD/nginx/config/stream.d:/etc/nginx/stream.d
    ports:
      - 80:80
