version: '3.9'

networks:
  php:
    external: false

services:
  php80:
    build:
      context: ./
      dockerfile: ./php80/Dockerfile
    image: php:80
    restart: always
    user: "${USERID:-1001}:${GID:-0}"
    networks:
      - php
    volumes: 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./conf/php80/fpm/php.ini:/etc/php/8.0/fpm/php.ini
      - ./conf/php80/cli/php.ini:/etc/php/8.0/cli/php.ini
      - ./conf/php80/fpm/docker.conf:/etc/php/8.0/fpm/pool.d/docker.conf
      - ./conf/php80/fpm/zz-docker.conf:/etc/php/8.0/fpm/pool.d/zz-docker.conf
      - /opt/www:/opt/www
    working_dir: /opt/www
  php74:
    build:
      context: ./
      dockerfile: ./php74/Dockerfile
    image: php:74
    restart: always
    user: "${USERID:-1001}:${GID:-0}"
    networks:
      - php
    volumes: 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./conf/php74/fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./conf/php74/cli/php.ini:/etc/php/7.4/cli/php.ini
      - ./conf/php74/fpm/docker.conf:/etc/php/7.4/fpm/pool.d/docker.conf
      - ./conf/php74/fpm/zz-docker.conf:/etc/php/7.4/fpm/pool.d/zz-docker.conf
      - /opt/www:/opt/www
    working_dir: /opt/www
